import type { Client, Project, TeamMember, Ticket, TicketUpdate } from "@/types";

// ─── Clients ─────────────────────────────────────────────────────────────────

export const DEMO_ADMIN: Client = {
  id: "demo-admin-id",
  name: "Axit Mehta",
  company: "Nerdshouse Technologies LLP",
  email: "admin@nerdshouse.in",
  is_admin: true,
  status: "active",
  created_at: "2024-01-01T00:00:00Z",
};

export const DEMO_CLIENTS: Client[] = [
  {
    id: "demo-client-id",
    name: "Priya Sharma",
    company: "Acme Corp",
    email: "priya@acme.com",
    is_admin: false,
    status: "active",
    created_at: "2024-01-15T00:00:00Z",
  },
  {
    id: "demo-client-2",
    name: "Rahul Verma",
    company: "Globex Inc",
    email: "rahul@globex.com",
    is_admin: false,
    status: "active",
    created_at: "2024-02-10T00:00:00Z",
  },
  {
    id: "demo-client-3",
    name: "Anika Patel",
    company: "Initech",
    email: "anika@initech.com",
    is_admin: false,
    status: "inactive",
    created_at: "2024-03-05T00:00:00Z",
  },
];

export const DEMO_CLIENT = DEMO_CLIENTS[0];

// ─── Projects ─────────────────────────────────────────────────────────────────

export const DEMO_PROJECTS: Project[] = [
  {
    id: "proj-1",
    name: "Acme Platform v2",
    client_id: "demo-client-id",
    color: "#4a4fe0",
    created_at: "2024-02-01T00:00:00Z",
    clients: { name: "Priya Sharma", company: "Acme Corp" },
  },
  {
    id: "proj-2",
    name: "Acme Mobile App",
    client_id: "demo-client-id",
    color: "#16a34a",
    created_at: "2024-03-10T00:00:00Z",
    clients: { name: "Priya Sharma", company: "Acme Corp" },
  },
  {
    id: "proj-3",
    name: "Globex ERP",
    client_id: "demo-client-2",
    color: "#ea580c",
    created_at: "2024-04-01T00:00:00Z",
    clients: { name: "Rahul Verma", company: "Globex Inc" },
  },
  {
    id: "proj-4",
    name: "Initech Dashboard",
    client_id: "demo-client-3",
    color: "#9333ea",
    created_at: "2024-05-12T00:00:00Z",
    clients: { name: "Anika Patel", company: "Initech" },
  },
];

// ─── Team members ─────────────────────────────────────────────────────────────

export const DEMO_TEAM_MEMBERS: TeamMember[] = [
  {
    id: "tm-1",
    name: "Axit Mehta",
    email: "axit@nerdshouse.in",
    role: "Admin",
    avatar_initials: "AM",
    status: "active",
    created_at: "2024-01-01T00:00:00Z",
    open_ticket_count: 3,
  },
  {
    id: "tm-2",
    name: "Sneha Joshi",
    email: "sneha@nerdshouse.in",
    role: "Developer",
    avatar_initials: "SJ",
    status: "active",
    created_at: "2024-02-01T00:00:00Z",
    open_ticket_count: 5,
  },
  {
    id: "tm-3",
    name: "Karan Nair",
    email: "karan@nerdshouse.in",
    role: "Developer",
    avatar_initials: "KN",
    status: "active",
    created_at: "2024-03-15T00:00:00Z",
    open_ticket_count: 2,
  },
  {
    id: "tm-4",
    name: "Divya Rao",
    email: "divya@nerdshouse.in",
    role: "Designer",
    avatar_initials: "DR",
    status: "active",
    created_at: "2024-04-01T00:00:00Z",
    open_ticket_count: 1,
  },
  {
    id: "tm-5",
    name: "Nikhil Bajaj",
    email: "nikhil@nerdshouse.in",
    role: "QA",
    avatar_initials: "NB",
    status: "inactive",
    created_at: "2024-05-01T00:00:00Z",
    open_ticket_count: 0,
  },
];

// ─── Tickets ──────────────────────────────────────────────────────────────────

export const DEMO_TICKETS: Ticket[] = [
  {
    id: "a1b2c3d4-0001-0000-0000-000000000001",
    title: "Login page throws 500 on expired magic link",
    description: "When an expired magic link is clicked, the page crashes with a 500 error instead of showing a friendly message. Steps: 1. Request a magic link. 2. Wait 10 minutes. 3. Click the link. Expected: friendly error. Actual: 500.",
    priority: "P0",
    status: "in_progress",
    type: "Bug",
    module: "Authentication",
    client_id: "demo-client-id",
    project_id: "proj-1",
    assignee_id: "tm-2",
    created_at: "2025-04-28T09:12:00Z",
    updated_at: "2025-05-06T14:30:00Z",
    clients: { name: "Priya Sharma", company: "Acme Corp", email: "priya@acme.com" },
    projects: { name: "Acme Platform v2", color: "#4a4fe0" },
    team_members: { name: "Sneha Joshi", avatar_initials: "SJ" },
  },
  {
    id: "a1b2c3d4-0002-0000-0000-000000000002",
    title: "Add bulk CSV export on the Reports page",
    description: "We need the ability to export filtered results as a CSV file from the Reports module.",
    priority: "P1",
    status: "open",
    type: "Feature",
    module: "Reports",
    client_id: "demo-client-id",
    project_id: "proj-1",
    assignee_id: null,
    created_at: "2025-05-01T11:00:00Z",
    updated_at: "2025-05-01T11:00:00Z",
    clients: { name: "Priya Sharma", company: "Acme Corp", email: "priya@acme.com" },
    projects: { name: "Acme Platform v2", color: "#4a4fe0" },
    team_members: undefined,
  },
  {
    id: "a1b2c3d4-0003-0000-0000-000000000003",
    title: "Dashboard takes 8s to load on first visit",
    description: "The dashboard is very slow on first load. Profiling shows N+1 queries on the summary cards.",
    priority: "P1",
    status: "review",
    type: "Performance",
    module: "Dashboard",
    client_id: "demo-client-id",
    project_id: "proj-1",
    assignee_id: "tm-3",
    created_at: "2025-04-20T08:45:00Z",
    updated_at: "2025-05-05T16:00:00Z",
    clients: { name: "Priya Sharma", company: "Acme Corp", email: "priya@acme.com" },
    projects: { name: "Acme Platform v2", color: "#4a4fe0" },
    team_members: { name: "Karan Nair", avatar_initials: "KN" },
  },
  {
    id: "a1b2c3d4-0004-0000-0000-000000000004",
    title: "Billing invoice PDF missing company logo",
    description: "The generated PDF invoices do not include our company logo.",
    priority: "P2",
    status: "open",
    type: "Bug",
    module: "Billing",
    client_id: "demo-client-id",
    project_id: "proj-2",
    assignee_id: null,
    created_at: "2025-05-03T13:20:00Z",
    updated_at: "2025-05-03T13:20:00Z",
    clients: { name: "Priya Sharma", company: "Acme Corp", email: "priya@acme.com" },
    projects: { name: "Acme Mobile App", color: "#16a34a" },
    team_members: undefined,
  },
  {
    id: "a1b2c3d4-0005-0000-0000-000000000005",
    title: "Slack integration for ticket notifications",
    description: "Add a Slack webhook integration so our team gets notified when a ticket status changes.",
    priority: "P2",
    status: "done",
    type: "Feature",
    module: "Integrations",
    client_id: "demo-client-id",
    project_id: "proj-1",
    assignee_id: "tm-1",
    created_at: "2025-04-10T10:00:00Z",
    updated_at: "2025-04-30T17:00:00Z",
    clients: { name: "Priya Sharma", company: "Acme Corp", email: "priya@acme.com" },
    projects: { name: "Acme Platform v2", color: "#4a4fe0" },
    team_members: { name: "Axit Mehta", avatar_initials: "AM" },
  },
  {
    id: "a1b2c3d4-0006-0000-0000-000000000006",
    title: "Two-factor authentication support",
    description: "Add optional 2FA (TOTP) for all users.",
    priority: "P1",
    status: "open",
    type: "Feature",
    module: "Authentication",
    client_id: "demo-client-id",
    project_id: "proj-2",
    assignee_id: "tm-2",
    created_at: "2025-05-04T09:00:00Z",
    updated_at: "2025-05-04T09:00:00Z",
    clients: { name: "Priya Sharma", company: "Acme Corp", email: "priya@acme.com" },
    projects: { name: "Acme Mobile App", color: "#16a34a" },
    team_members: { name: "Sneha Joshi", avatar_initials: "SJ" },
  },
  {
    id: "a1b2c3d4-0007-0000-0000-000000000007",
    title: "Mobile app crashes on iOS 17.4 when opening Settings",
    description: "After updating to iOS 17.4, the mobile app crashes immediately when tapping the Settings tab.",
    priority: "P0",
    status: "open",
    type: "Bug",
    module: "Mobile",
    client_id: "demo-client-id",
    project_id: "proj-2",
    assignee_id: "tm-3",
    created_at: "2025-05-06T07:30:00Z",
    updated_at: "2025-05-06T07:30:00Z",
    clients: { name: "Priya Sharma", company: "Acme Corp", email: "priya@acme.com" },
    projects: { name: "Acme Mobile App", color: "#16a34a" },
    team_members: { name: "Karan Nair", avatar_initials: "KN" },
  },
  {
    id: "a1b2c3d4-0008-0000-0000-000000000008",
    title: "ERP export fails for datasets > 10k rows",
    description: "The ERP data export hangs and eventually times out when the dataset exceeds 10,000 rows.",
    priority: "P0",
    status: "open",
    type: "Bug",
    module: "Reports",
    client_id: "demo-client-2",
    project_id: "proj-3",
    assignee_id: "tm-2",
    created_at: "2025-05-05T10:00:00Z",
    updated_at: "2025-05-05T10:00:00Z",
    clients: { name: "Rahul Verma", company: "Globex Inc", email: "rahul@globex.com" },
    projects: { name: "Globex ERP", color: "#ea580c" },
    team_members: { name: "Sneha Joshi", avatar_initials: "SJ" },
  },
  {
    id: "a1b2c3d4-0009-0000-0000-000000000009",
    title: "Dark mode for the dashboard",
    description: "Please add a dark mode toggle to the main dashboard.",
    priority: "P2",
    status: "open",
    type: "Feature",
    module: "Dashboard",
    client_id: "demo-client-3",
    project_id: "proj-4",
    assignee_id: "tm-4",
    created_at: "2025-05-02T14:00:00Z",
    updated_at: "2025-05-02T14:00:00Z",
    clients: { name: "Anika Patel", company: "Initech", email: "anika@initech.com" },
    projects: { name: "Initech Dashboard", color: "#9333ea" },
    team_members: { name: "Divya Rao", avatar_initials: "DR" },
  },
];

export const DEMO_UPDATES: Record<string, TicketUpdate[]> = {
  "a1b2c3d4-0001-0000-0000-000000000001": [
    { id: "u1", ticket_id: "a1b2c3d4-0001-0000-0000-000000000001", message: "Reproduced the issue. The token expiry check is missing a redirect. Fix in progress — expected EOD.", author_type: "team", author_name: "Sneha Joshi", created_at: "2025-05-06T10:00:00Z" },
    { id: "u2", ticket_id: "a1b2c3d4-0001-0000-0000-000000000001", message: "Thank you! This is blocking our onboarding flow — please prioritise.", author_type: "client", author_name: "Priya Sharma", created_at: "2025-05-06T11:30:00Z" },
  ],
  "a1b2c3d4-0003-0000-0000-000000000003": [
    { id: "u3", ticket_id: "a1b2c3d4-0003-0000-0000-000000000003", message: "Identified the N+1 query on summary cards. Refactored to a single aggregation query. PR up for review.", author_type: "team", author_name: "Karan Nair", created_at: "2025-05-05T16:00:00Z" },
  ],
  "a1b2c3d4-0005-0000-0000-000000000005": [
    { id: "u4", ticket_id: "a1b2c3d4-0005-0000-0000-000000000005", message: "Slack integration is live! Configure the webhook in Settings → Integrations → Slack.", author_type: "team", author_name: "Axit Mehta", created_at: "2025-04-30T17:00:00Z" },
  ],
};
